services:
  app:
    build: .
    container_name: numericollection
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./storage.db:/data/storage.db
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:////data/storage.db

volumes: {}
