rarities = [
  "COMUNE",
  "RARA",
  "SUPER RARA",
  "ULTRA RARA",
  "SEGRETA RARA",
  "PRISMATICA SEGRETA",
  "ULTIMATE RARA",
  "ULTIMATE RARA PRISMATICA",
  "RARA DA COLLEZIONISTA",
  "RARA FANTASMA",
  "RARA STARLIGHT",
  "RARA SEGRETA DEL QUARTO DI SECOLO",
  "RARA ORO SEGRETA",
  "ORO PREMIUM",
]

conditions = [
  "POOR",
  "PLAYED",
  "LIGHT PLAYED",
  "GOOD",
  "EXCELLENT",
  "NEAR MINT",
  "MINT",
]
